export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';

export const APPROVE_COMMENTS = 'APPROVE_COMMENTS';
export const REJECT_COMMENTS = 'REJECT_COMMENTS';

export const LOADING_COMMENTS = 'LOADING_COMMENTS';
